name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: golang:1.16-alpine3.13
    steps:
      - name: Install pre-requisites (1)
        run: |
          apk add --no-cache make jq zip curl git npm gettext

      - name: Install pre-requisites (2)
        run: |
          go get github.com/github/hub

      - name: Checkout
        uses: actions/checkout@master

      - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"

      - name: Build binaries
        run: make binaries

      - name: Release version
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          rm -rf .git/index.lock
          npm version patch
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN  }}
