name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: golang:1.15.6-alpine
    steps:
      - name: Install pre-requisites (1)
        run: |
          apk add --no-cache make jq zip curl git npm
      - name: Install pre-requisites (2)
        run: |
          subst_version="1.1.1"
          curl -sSLO https://github.com/sgreben/subst/releases/download/${subst_version}/subst_${subst_version}_linux_x86_64.zip
          unzip subst_${subst_version}_linux_x86_64.zip
          mv subst /usr/local/bin
      - name: Install pre-requisites (3)
        run: |
          go get github.com/github/hub
      - name: Checkout
        uses: actions/checkout@master
      - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"
      - name: Build
        run: make binaries
      - name: Release
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          npm version patch
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
